import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/store/StoreProvider";
import { Providers } from "./ThemeProvider";
import { Toaster } from "react-hot-toast";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";

// Load the Inter font with the Latin subset
const inter = Inter({ subsets: ["latin"] });

// Metadata for the app
export const metadata: Metadata = {
    title: "LUS Annotation Platform",
    description: "Generated by create next app",
};

// This is the root layout component that wraps the entire application.
// It provides the session context to all components, also the Redux store context, the Toaster for toast messages, and the theme context.
// The layout component is usually UI shared across multiple pages.
export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    // Get the session
    const session = await auth();
    return (
        <SessionProvider session={session}>
            <html lang="en" suppressHydrationWarning>
                <body className={inter.className}>
                    <Toaster position="bottom-center" reverseOrder={false} />
                    <StoreProvider>
                        <Providers>{children}</Providers>
                    </StoreProvider>
                </body>
            </html>
        </SessionProvider>
    );
}
