version: "3.8"
secrets:
    mongo-user:
        file: ./mongo/mongo-user
    mongo-pass:
        file: ./mongo/mongo-pass

services:
    mongo-db:
        container_name: mongo-db
        image: mongo:latest
        restart: always
        environment:
            MONGO_INITDB_DATABASE: thesis
            MONGO_INITDB_USERNAME: mongo-user
            MONGO_INITDB_PASSWORD: mongo-pass

        ports:
            - 27017:27017


        secrets:
            - mongo-user
            - mongo-pass

        volumes:
            - ./mongo/data/db:/data/db
            - ./mongo/data/config:/data/configdb
            - ./mongo/init_mongo.js:/docker-entrypoint-initdb.d/init_mongo.js
            - ./mongo/mongo-keyfile:/opt/keyfile/mongo-keyfile
            - ./mongo/mongod.conf:/etc/mongod.conf
        
        command: ["-f", "/etc/mongod.conf"]
